# Generated by Django 4.2 on 2023-05-02 17:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(limit_value=10)])),
                ('qualification', models.CharField(max_length=50)),
                ('experience_years', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('time', models.CharField(max_length=25)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training_app.instructor')),
            ],
        ),
    ]
