# Generated by Django 4.2 on 2023-05-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name_plural': 'Instructor'},
        ),
    ]
