# Generated by Django 4.2 on 2023-05-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0002_alter_instructor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='upcomingclass',
            options={'verbose_name_plural': 'UpcomingClasses'},
        ),
        migrations.AlterModelTable(
            name='instructor',
            table='Instructor',
        ),
        migrations.AlterModelTable(
            name='upcomingclass',
            table='UpcomingClass',
        ),
    ]
