# Generated by Django 4.2 on 2023-05-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0003_alter_instructor_options_alter_upcomingclass_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('level', models.CharField(max_length=1)),
            ],
        ),
    ]
