# Generated by Django 4.2 on 2023-05-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0006_alter_course_options_alter_course_level_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={},
        ),
        migrations.AlterModelTable(
            name='courses',
            table='Courses',
        ),
    ]
