# Generated by Django 4.2 on 2023-05-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0007_rename_course_courses_alter_courses_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='delete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelTable(
            name='courses',
            table='courses',
        ),
    ]
